# Generated by Django 5.0 on 2023-12-30 09:50

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[accounts.models.PhoneNumberValidator]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default=None, upload_to='profiles/'),
        ),
    ]
