# Generated by Django 3.2.20 on 2024-01-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verified_drive',
            field=models.BooleanField(default=False),
        ),
    ]
