# Generated by Django 3.2.20 on 2024-01-06 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_verified_drive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='verified_drive',
            new_name='verified_driver',
        ),
    ]
