# Generated by Django 5.0 on 2024-01-29 16:51

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RideModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_available', models.IntegerField()),
                ('departure_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('destination_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('departure_time', models.DateTimeField()),
                ('fare', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('passengers', models.ManyToManyField(blank=True, related_name='rides_as_passenger', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
