# Generated by Django 5.0 on 2024-01-31 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridemodel',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('onway', 'On Way'), ('completed', 'Completed')], default='upcoming', max_length=20, null=True),
        ),
    ]
