# Generated by Django 4.2.8 on 2024-01-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aadharcardmodel',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='drivinglicensemodel',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='imagewithvehiclemodel',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
