# Generated by Django 4.2.8 on 2024-01-09 21:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_aadharcardmodel_message_drivinglicensemodel_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadharcardmodel',
            name='document',
            field=models.FileField(upload_to='document_uploads/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='drivinglicensemodel',
            name='document',
            field=models.FileField(upload_to='document_uploads/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='imagewithvehiclemodel',
            name='document',
            field=models.FileField(upload_to='document_uploads/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
