# Generated by Django 5.0 on 2024-01-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_aadharcardmodel_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagewithvehiclemodel',
            name='plate_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='imagewithvehiclemodel',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='imagewithvehiclemodel',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('2W', '2 Wheeler'), ('4W', '4 Wheeler')], max_length=2, null=True),
        ),
    ]
